name:                BrainFuckParser
version:             0.0.0.1
github:              "fusiled/BrainFuckParser"
license:             BSD3
author:              "fusiled"
maintainer:          "fusiled@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fusiled/BrainFuckParser#readme>

dependencies:
- base >= 4.7 && < 5
- word8
- parsec

library:
  source-dirs: src

executables:
  BrainFuckParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BrainFuckParser

tests:
  BrainFuckParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BrainFuckParser
